### PR TITLE
Mridup

### PR DESCRIPTION
**Pull request by mridup**
Azure Edge ST-SDK draft
1. Examples with BLE module toggle switch form one device to another
2. FW upgrade + Ai event reporting to dashboard (transparent GW)

### CODE REVIEW

**Comment by mridup** [comment]
The README.md in the main root folder has some issue due to which the pypi packaging fails while uploading. This still needs to be fixed.

**Comment by mridup** [comment]
master merged in mridup

**Comment by mridup** [comment]
Changed repo name. tested working with stmedge.azurecr.io/modaievt_tpgw:0.0.1-arm32v7.

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Pull request closed without merging**
